title: "Asif Syed | ML Scientist"
subtitle: "ML Scientist"
url: "https://asifbinsyed.github.io"
repository: "Asifbinsyed/asifbinsyed.github.io"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #
#url_logo: "the-home-depot.png"

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

# sass:
#     style: compressed
#     sass_dir: _sass
remote_theme: ankitsultana/researcher@gem

nav:
 - name: "About"
   link: "/asifbinsyed.github.io/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
